FROM alpine:3.6
RUN apk --update add openjdk7-jre
#CMD ["/usr/bin/java", "-version"]
#RUN mkdir -p /app/demo
#WORKDIR /app/demo
#COPY demoSpringBoot.jar /app/demo/
#EXPOSE 8080
#CMD ["/usr/bin/java","-jar","demoSpringBoot.jar"]
