# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    #config.vm.box = "ubuntu/xenial64"
    config.vm.box = "centos/7"
    config.vm.hostname = "registry"
    config.vm.network :private_network, ip: "192.168.10.25", mac: "5CA1AB1E0001"
    config.vm.network :forwarded_port, guest: 22, host: 2225, id: "ssh", auto_correct:true
    config.vm.network :forwarded_port, guest: 5000, host: 5000, id: "registry", auto_correct:true
    config.vm.network :forwarded_port, guest: 8080, host: 8080, id: "registry-ui2", auto_correct:true

    config.vm.box_check_update = false
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
        v.customize ["modifyvm", :id, "--audio", "none"]
    end
    config.vm.provision "shell", path: "provision.sh"
end
