---
version: '3.0'
services:
  oracle-xe:
#    build: .
    image: dannybastos/oracle-11g-xe
    restart: always
    ports:
      - "8080:8080"
      - "1521:1521"
    volumes:
      - oracle-db-data:/u01/app/oracle/product/11.2.0/xe/dbs
volumes:
  oracle-db-data:
