#
version: '3.1'

services:
  db:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test11
      MYSQL_USER: test11
      MYSQL_PASSWORD: test11
    volumes:
      - ./data:/var/lib/mysql

    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# volumes:
#   data-volume:
