# Use root/example as user/password credentials
version: '3'

services:

  keycloak:
    image: dannybastos/keycloak:18.0.2
    build: .
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: secret
    ports:
      - 8080:8080
    restart: unless-stopped
